frase2 = dict()
frase = 'o rato matheus roeu o queijo do rato estefani'.strip().split()
frase2['o'] = frase.count('o')
frase2['rato'] = frase.count('rato')
frase2['matheus'] = frase.count('matheus')
frase2['roeu'] = frase.count('roeu')
frase2['queijo'] = frase.count('queijo')
frase2['do'] =  frase.count('do')
frase2['estefani'] = frase.count('estefani')
print(frase2)