n1 = (input('Digite algo : '))

print(f'O tipo primitivo desse valor é {type(n1)}')
print(f'Só tem espaços? {n1.isspace()}')
print(f'É um número? {n1.isnumeric()}')
print(f'É alfabético? {n1.isalpha()}')
print(f'É alfanúmerico? {n1.isalnum()}')
print(f'Está em letras maiúsculas? {n1.isupper()}')
print(f'Está em letras minúsculas? {n1.islower()}')
print(f'Está capitalizada? {n1.istitle()}')